version: "3.8"

services:
  redis:
    container_name: redis
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend-network

  backend:
    container_name: backend
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - app_logs:/app/logs
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    networks:
      - backend-network

networks:
  backend-network:
    name: backend-network

volumes:
  redis_data:
  app_logs: